version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dfcu_payment_gateway
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dfcu-network

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=dfcu_payment_gateway
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d dfcu_payment_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dfcu-network

volumes:
  postgres_data:

networks:
  dfcu-network:
    driver: bridge 