# src/main/resources/application-prod.yml

spring:
  datasource:
    # Heroku provides the JDBC_DATABASE_URL, JDBC_DATABASE_USERNAME & JDBC_DATABASE_PASSWORD
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000        # 5 minutes
      connection-timeout: 20000   # 20 seconds

  jpa:
    # Let Spring Boot pick the correct dialect from the JDBC URL
    hibernate:
      ddl-auto: update
    show-sql: false                # Disable SQL logging in production

server:
  port: ${PORT:8080}               # Heroku provides the PORT env var
  tomcat:
    max-threads: 200
    min-spare-threads: 10

# CORS Configuration
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Logging
logging:
  level:
    root: INFO
    dfcu.app: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
