spring:
  datasource:
    # Heroku provides JDBC_DATABASE_URL, USERNAME & PASSWORD
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      connection-timeout: 20000 # 20 seconds
  jpa:
    hibernate:
      ddl-auto: validate  # Safer for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false  # Disable SQL logging in production

server:
  port: ${PORT:8080}  # Heroku provides PORT environment variable
  tomcat:
    max-threads: 200
    min-spare-threads: 10

# CORS Configuration for production
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-frontend-domain.com}

# Logging
logging:
  level:
    root: INFO
    dfcu.app: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"