# src/main/resources/application-prod.yml

spring:
  datasource:
    # Heroku provides these environment variables:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000        # 5 minutes
      connection-timeout: 20000   # 20 seconds

  jpa:
    # If you still want to explicitly set the dialect, uncomment the next line.
    # Make sure there is NO trailing space after the class name!
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
    show-sql: false                # disable SQL logging in production

server:
  port: ${PORT:8080}               # Heroku sets PORT for you
  tomcat:
    max-threads: 200
    min-spare-threads: 10

# CORS Configuration (populated via your env var)
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Logging
logging:
  level:
    root: INFO
    dfcu.app: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
