name: Deploy to Heroku via Docker

# ← triggers on every push to main
on:
  push:
    branches:
      - main

# ← expose your secrets to all steps
env:
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }}
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) grab your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3) setup Maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      # 4) build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4) install Heroku CLI (needed for `